name: 3D Digital Art and Design Open Education Resource
author: Michael Collins
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "lax_spacing"]
baseurl: /3d-modeling-rendering-animation-sp18--oer
permalink: pretty
markdown: kramdown
timezone: America/New_York
future: true
plugins:
  - jekyll-sitemap
# Github links
github-repo: https://github.com/michael-collins/3d-modeling-rendering-animation-sp18--oer
#directoy config ########################################
#collections_dir: all_collections
collections:
  agenda:
    output: true
    permalink: /agenda/:title.html
  lessons:
    output: true
    permalink: /lessons/:title.html
  exercises:
    output: true
    permalink: /exercises/:title.html
  projects:
    output: true
    permalink: /projects/:title.html
  grading:
    output: true
    permalink: /grading/:title.html
  syllabus:
    output: true
    permalink: /syllabus/:title.html
  topics:
    output: true
    permalink: /topics/:title.html
#exercises ########################################
assignments:
  exercise-1:
    due-date: 2:30pm on January 11, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-1
    title: Exercise 1
    doc: /exercises/maya-image-planes-for-modeling.html
  exercise-2:
    due-date: 2:30pm on January 16, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-2
    title: Exercise 2
    doc: /exercises/maya-modeling.html
  exercise-3:
    due-date: 2:30pm on January 23, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-3
    title: Exercise 3
    doc: /exercises/maya-texturing.html
  exercise-4:
    due-date: 2:30pm on January 25, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-4
    title: Exercise 4
    doc: /exercises/maya-arnold-lighting-and-rendering.html
  exercise-5:
    due-date: 2:30pm on January 30, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-5
    title: Exercise 5
    doc: /exercises/maya-mentalray-ibl.html
  exercise-6:
    due-date: 2:30pm on March 15, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-6
    title: Exercise 6
    doc: /exercises/maya-animation.html
  exercise-7:
    due-date: 2:30pm on March 20, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-7
    title: Exercise 7
    doc: /exercises/maya-rigging.html
  exercise-8:
    due-date: 2:30pm on March 27, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-8
    title: Exercise 8
    doc: /exercises/maya-animated-textures.html
  exercise-9:
    due-date: 2:30pm on April 3, 2018
    dropbox-url: https://psu.box.com/v/art314sp18-exercise-9
    title: Exercise 9
    doc: /exercises/dynamics.html
  project-1:
    doc: /projects/speculative-design.html
    concepts:
      due-date: 2:30pm on February 1, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-concepts
      title: Project 1 Concepts
    wireframes:
      due-date: 2:30pm on February 8, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-wireframes
      title: Project 1 Wireframes
    look-development:
      due-date: 2:30pm on February 13, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-look-dev
      title: Project 1 Look Development
    draft-renders:
      due-date: 2:30pm on February 15, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-draft-renders
      title: Project 1 Draft Renders
    draft-statement:
      due-date: 2:30pm on February 22, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-draftstatement
      title: Project 1 Draft Statement
    final-statement:
      due-date: 2:30pm on February 27, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-finalstatement
      title: Project 1 Final Statement
    final-submission:
      due-date: 2:30pm on February 27, 2018
      dropbox-url: https://psu.box.com/v/art314sp18-pr-1-submission
      title: Project 1 Final Submission
  # - exercise: maya-modeling-image-planes
  #   title: Intro to Modeling in Maya
  #   subtitle: testing config
  #   submission_link: 
  #   comments_enabled:
  #   published: true
  #   assigned: 1/14/2016
  #   due: 1/19/2016
  # - exercise: maya-texturing-objects
  #   title: Intro to Texturing in Maya
  #   subtitle: testing config
  #   submission_link: 
  #   comments_enabled:
  #   published: true
  #   assigned: 1/19/2016
  #   due: 1/21/2016
  # - exercise: maya-animation-animating
  #   title: Animating in Maya
  #   subtitle:
  #   submission_link: 
  #   comments_enabled:
  #   published: true
  #   assigned: 1/26/2016
  #   due: 1/28/2016
#topics  ########################################
topics:
  - topic: modeling
    title: Animating in Maya
    layout: topic
    submission_link: 
    comments_enabled:
    published: true
    assigned: 1/26/2016
    due: 1/28/2016
#lessons  ########################################
course:
  unit:
    lessons:
      - lesson: maya-modeling
        title: Modeling in Maya
        subtitle: testing config
        layout: lesson
        submission_link: 
        comments_enabled:
        published: true
        assigned: 1/26/2016
        due: 1/28/2016
      - lesson: maya-animation
        subtitle: testing config
        title: Texturing in Maya
        layout: lesson
        submission_link: 
        comments_enabled:
        published: true
        assigned: 1/26/2016
        due: 1/28/2016
